MERGE INTO JUROR.SYSTEM_PARAMETER USING DUAL ON (SP_ID=100)
  WHEN MATCHED THEN UPDATE SET SP_DESC='Upper Age Limit', SP_VALUE=60, CREATED_BY='CUCUMBER', UPDATED_BY='CUCUMBER';
MERGE INTO JUROR.SYSTEM_PARAMETER USING DUAL ON (SP_ID=101)
  WHEN MATCHED THEN UPDATE SET SP_DESC='Lower Age Limit', SP_VALUE=25, CREATED_BY='CUCUMBER', UPDATED_BY='CUCUMBER';
