BEGIN
  DELETE FROM JUROR.PASSWORD;
  DELETE FROM JUROR_DIGITAL.BUREAU_AUTH;
  --
  -- juror responses
  DELETE FROM JUROR.PART_HIST;
  DELETE FROM JUROR.PART_AMENDMENTS;
  DELETE FROM JUROR.PHONE_LOG;
  DELETE FROM JUROR.POOL;
  DELETE FROM JUROR.UNIQUE_POOL;
  DELETE FROM JUROR_DIGITAL.POOL_EXTEND;
  DELETE FROM JUROR_DIGITAL.JUROR_RESPONSE_CJS_EMPLOYMENT;
  DELETE FROM JUROR_DIGITAL.JUROR_RESPONSE_SPECIAL_NEEDS;
  DELETE FROM JUROR_DIGITAL.CHANGE_LOG_ITEM;
  DELETE FROM JUROR_DIGITAL.CHANGE_LOG;
  DELETE FROM JUROR_DIGITAL.JUROR_RESPONSE;
  DELETE FROM "JUROR_DIGITAL"."JUROR_RESPONSE_AUD";
  DELETE FROM "JUROR_DIGITAL"."COURT_WHITELIST";
  --
  -- standing data
  DELETE FROM JUROR_DIGITAL.APP_SETTINGS;
  MERGE INTO JUROR.SYSTEM_PARAMETER USING DUAL ON (SP_ID=100)
    WHEN NOT MATCHED THEN INSERT (SP_ID, SP_DESC, SP_VALUE, CREATED_BY, UPDATED_BY) VALUES (100,'Upper Age Limit',76,'SYS','SYS')
    WHEN MATCHED THEN UPDATE SET SP_VALUE=76, CREATED_BY='SYS', UPDATED_BY='SYS';
  MERGE INTO JUROR.SYSTEM_PARAMETER USING DUAL ON (SP_ID=101)
    WHEN NOT MATCHED THEN INSERT (SP_ID, SP_DESC, SP_VALUE, CREATED_BY, UPDATED_BY) VALUES (101,'Lower Age Limit',18,'SYS','SYS')
    WHEN MATCHED THEN UPDATE SET SP_VALUE=18, CREATED_BY='SYS', UPDATED_BY='SYS';
END;
